### ISSUE TITLE
Javascript Extensions API

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1020]
This feature will allow developers to integrate a custom Javascript hook on every outgoing HTTP requests and incoming HTTP responses. The developer can intercept these requests and body to modify them or trigger new requests or responses.

**Proposal V1**
The design is highly inspired from [Cloudfront Functions] but comes with additional capabilities and a more powerful JS runtime. 
The script would have the function of the following signature:

```ts
type Headers = {[name: string]: string}

type Request = {
  url: string,
  headers: Headers,
  body: string
}

type Response = {
  status: number,
  headers: Headers,
  body: string
}

type Event = Request | Array<Response>
type Command = Array<Request> | Response

function onEvent(event: Event): Command {
   // Can modify the request
}
```

- [ ] Add Timeout @meskill  #1005
- [x] Integration tests for script execution #1005
- [x] Remove `unwraps` #1005
- [x] Add Closure #1005
- [x] Client Integration #1005
- [x] Link JS via HTTP/File #1005
- [x] `Request` + `Response` codecs for `mini_v8::Value` #1005
- [x] Unit Test for Script Loading #1005
- [x] `Config.merge_right` #1005
- [x] Handle empty command #1005
- [x] Fix `IOException` on n + 1 #1005
- [x] WASM CI Fix #1005
- [x] Use `deno_core` instead of `mini_v8` ##1088
- [x] Drop existing JS "unsafe-js" integration
- [x] Move `Event` and `Command` in their files.
- [x] Use `serde_v8` instead of custom implementation #1088
- [x] Delete MiniV8 Code #1088
- [x] `console.log` support
- [ ] support source_map
- [ ] Support `fetch` @meskill 
- [x] Unit Tests for JsRequest, JsResponse codecs
- [ ] JS Threadpool vs Tokio Worker Threadpool options @meskill 
- [ ] Micro Benchmarks
- [ ] Whitelist/Blacklist of HTTP calls
- [ ] Add Typescript SDK
~Store Closure in Blueprint~
- [ ] Script validation at the time of loading @meskill 
- [ ] Lazy Request/Response Body
- [ ] WASM Compat
- [ ] Moving `@server {script}` to `@link` #1103
- [ ] Headers should be sent to and from jsruntime `bytes`
- [ ] Unit test for `runtime` and `http_filter`

**Links**
- [Cloudfront Function Schema](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/functions-event-structure.html)
- [Typescript Schema for CFF](https://www.npmjs.com/package/@types/aws-cloudfront-function)

[Cloudfront Functions]: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cloudfront-functions.html

**Comment by tusharmath** [comment]
After spending many hours/days trying to optimize the JS integration with Tailcall, we have come to realize there are a few issues with all JS runtimes.
- We tried - mini_v8, deno_core, and rquickjs and they all have similar problems.
- None of them are thread-safe, and a lot of thread management needs to be done by tailcall to make it work.
- The main performance degradation is when we need to move Request and Response body into the JS real and then even bigger degradation happens when we need to parse that body and transform it.
- Adding async support in JS requires a full-fledged event-loop integration. Which seems like an overkill architecturally and again impact performance.
- We also see the application size increase by 20Mb when we embed v8. V8 also doesn't work on a platforms and hence has to be disabled on those.
For the above reasons I propose a simpler yet effective API to integrate JS

**Proposal V2**
The key modifications are —
1. We will make sure only sync API is supported via JS, meaning no fetch, not setTimeout etc.
2. We will never pass the whole request or response body to the JS side. Passing complete body to the JS side, makes our solution perform very poorly. I would rather build a custom Rust based proxy for very specialized orchestration requirements and run it as a side car with Tailcall.
3. We will provide an API to call js by function names instead. We should be able to do that not only for HTTP resolvers but also for any arbitrary graphQL field.

```graphql

schema
  # Link a JS worker into the tailcall 
  @link(src: "worker.js" type: Worker)
  
  # Add onRequest and onResponse handlers of upstream
  @upstream(script: {onRequest: "onRequest", onResponse: "onResponse"}) {
  query: Query
}


type Query {
  # Special js handlers added to override the ones set by default in upstream
  users: [User] @http(path: "/users", onRequest: "onUsersRequest", onResponse: "onUsersResponse")
}

type User {
  id: ID
  
  # This is a usecase where allow performing any arbitrary JS transformations
  # `toUpperCase` should get a lazily encoded `ctx` object as a parameter.
  name: String @script(name: "toUpperCase")
  address: Address
}
```

**Technical Requirements**
Use https://docs.rs/rquickjs/0.5.0 instead of v8 for it's size and faster bootup time.

**Comment by meskill** [comment]
> Proposal V2

How the `onResponse` and `onUserResponse` should work in that case? Do they also get response body, or only other response info like status and headers? If they do it's sounds like the same problem that can drop performance significantly depending on usecase. For cases when upstream returns list of data and we want to filter it from js feels like deserialization should happen anyway...
Also for `@script` does it accept ctx with all fields from parent value or only the value for field it's defined on? 
Any ideas on how the laziness should be implemented? for deno_core passing the string involved copying all the time, bytes are almost free but its slow to parse on js side. deno using approach of decoding bytes to string with rust function that is called from js when needed and I wonder how that affects performance because that means many context switching from rust to js and backward for every entry in response lists
