### ISSUE TITLE
Restructure Workspace

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1153]
High-Level Structure of workspace

```bash
/core           #publish on Crates
/core-runtime   #publish on Crates
/integration    #integration tests
/main-cli       #cli application
/main-aws-lambda
/main-cloudfare
/main-fastly
/main-web
/main-node

/main-azure    #personal project
```

- [ ] Create a `TailcallBuilder` in `src/builder.rs` (#1195)
- [ ] Migrate unit tests to `TailcallBuilder`
- [x] Separate Test IO (#1165)
- [ ] Make all `src/lib.rs` type crate private.
- [ ] Refactor everywhere to use `TailcallBuilder`
- [x] Drop `dyn HttpIO` and other IO from types and refer them to use TargetRuntime instead. (#1155)
