### ISSUE TITLE
feat: Add @validate directive for custom scalar validation

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcall#1847]
**Description:**
Currently, Tailcall allows developers to define custom scalars. However, there's no built-in way to add validations on those custom scalars. I propose creating a `@validate` directive which takes js function as input and can be applied on scalars. The js function inside `@validate` should return either `true` or `false`. If it returns `false`, the user should receive a Evaluation error when an invalid value is passed into the scalar.

**Expected Behavior:**
- The `@validate` directive should be applicable to custom scalar types.
- The directive js function should return `true` for valid values and `false` for invalid values.
- If the directive returns `false`, a Evaluation error should be thrown to indicate the issue to the user.

**Tasks:**
- [ ] Implement a `@validate` directive that developers can use on custom scalars.
- [ ] @validate accepts a js function as input.
- [ ] errors should follow the formatting guidelines of Tailcall Evaluation Errors

**Example**

```graphql
scalar EvenNumber @validate(js: "isEven")
```

```js
function isEven(num) {
	return num % 2 === 0
}
```

**Comment by webbdays** [comment]
@mobley-trent 
are you still on this?

**Comment by mobley-trent** [comment]
Feel free to pick up the issue @webbdays

**Comment by Shylock-Hg** [comment]
@tusharmath to do this, we need to create a separate Js Worker when validate `Config` and run js script when generate `Blueprint`. Is it ok?
