### ISSUE TITLE
[master] redesign configuration Interface

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#3164]
- [ ] Split runtime config and schema config
- [ ] Create schema config from ServiceDocument
- [ ] Validation should contain position information
- [ ] Merge should only happen for schema config
- [ ] CLI should take schema and runtime config separately

**Comment by tusharmath** [comment]
To split configurations we can consider the following refactor on Config


```rust

// After (v2)
pub enum Config {
    SchemaConfig(SchemaConfig),
    RuntimeConfig(RuntimeConfig),
}

// Merge only Schema
pub struct SchemaConfig {
    pub schema: RootSchema,
    pub types: BTreeMap<String, Type>,
    pub unions: BTreeMap<String, Union>,
    pub enums: BTreeMap<String, Enum>,  
}

pub struct RuntimeConfig {
    pub server: Server,
    pub upstream: Upstream,
    pub telemetry: Telemetry,
    pub links: Vec<Link>,    
}
```

**Comment by tusharmath** [comment]
**Phase 1**

- [ ] Merge on Config should ignore server, upstream and telemetry (Alphabetical order).
- [ ] server, upstream and telemetry should be read from root configuration.
- [ ] Merge directives (Make all directives repeatable).
- [ ] Merge links into root configuration.

**Comment by meskill** [comment]
pr https://github.com/tailcallhq/tailcall/pull/3190 for phase 1

For phase 2 the multiple directives are already done by https://github.com/tailcallhq/tailcall/pull/3124

**Comment by meskill** [comment]
> * Make Config sub-type of ServiceDocument

What does it mean?

**Comment by meskill** [comment]
pr https://github.com/tailcallhq/tailcall/pull/3201 to drop support of json/yaml configs
