### ISSUE TITLE
🚀 Tailcall Mini Hackathon: Bringing WASM to the Party with $2000 Bounty! 🎉

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#750]
**Existing Functionality**
- [x] Entity Cache (#966)
- [x] HTTP Support (#892)
- [x] Implement `FileIO` via assets or buckets for cloudflare (#926)
- [x] Http Batching (#997)
- [x] HTTP Caching (Powered by cloudflare already)
- [x] GRPC support (#1041)

**Architecture**
- [x] Support for multi-tenant deployment (#991)
- [x] Add support for static io (#941)
- [x] Add support for loading config from url path (#980)
- [x] Create an IO Abstraction that supports File and Network (#914)
- [x] Add panic hook (#996)
- [x] Support Relative Paths in config reader (Out of scope)
- [x] Remove hard-coded tailcall config URL
- [ ] Remove feature flags for cargo.toml
- [ ] Update package structure — `cli`, `cloudflare`, `core`
- [ ] Drop usage of `default` feature flag (CLI work is pending)
- [x] Remove GRPC specific client APIs that take Protobuf as Input.
- [x] Merge `HttpClientOptions` with `Upstream`
- [x] Add `EnvIO` 
- [x] Review usage of `set_req_version`
- [x] Add unit tests/test for cloudflare response (#1016 )
- [x] Add HTML response for ValidationErrors
- [ ] Interface with async_graphql Req/Res instead of going via hyper
- [x] Move `Env` to test
- [ ] Drop `spawn_local` from `cloudflare::Http`
---

## Later
- [ ] Use `impl HttpIO` instead of `dyn HttpIO`
---

🌟 **Calling All Code Wizards: Tailcall Mini Hackathon Awaits! 🧙‍♂️💻**

We're on a quest to bring WASM to Tailcall, and we're rolling out the red carpet for developers far and wide! With a whopping $2000 bounty for the winner, this is your chance to dive into Rust, WebAssembly, and Cloudflare, and make a lasting impact. 🏆💼

**Your Challenge:**
- Bring WASM support to Tailcall for Cloudflare deployment.
- Ensure no performance dip and full feature functionality.
- Be the hero Tailcall needs!

**Why You Can't Miss This:**
- **$2000 Bounty:** A grand prize for the winner to sweeten the deal.
- **Community and Collaboration:** Join forces with fellow developers in our Discord community.
- **Gain Visibility:** By starring our repository, you help boost its prominence and your own profile.
- **Real Impact:** Your contribution could shape the future of API ecosystem.
- **Job Opportunity:** Impress us, and you could land a job offer with Tailcall.

**Join the Adventure:**
1. **Star the Repository:** A simple star can make a big difference. Show your support!
2. **Fork, Code, Conquer:** Dive into the code and let your skills shine.
3. **Join Our Discord:** Connect, collaborate, and celebrate your progress with us at [https://discord.gg/Q2ZExpFCnA](https://discord.gg/Q2ZExpFCnA).

**Ready to Start?**
- Gear up with Cloudflare's Rust and WASM guide: [https://developers.cloudflare.com/workers/runtime-apis/webassembly/rust/](https://developers.cloudflare.com/workers/runtime-apis/webassembly/rust/)
- Explore Tailcall and envision its transformation.

Are you ready to embark on this epic journey, claim the bounty, and etch your name in the annals of open-source history? Let's hackathon! 🌐🚀🎈

<img referrerpolicy="no-referrer-when-downgrade" src="https://static.scarf.sh/a.png?x-pxid=f7b796f7-e914-40b9-aa7e-b090f3064f90" />

---

_Don't just code; create a revolution. Star, join, code, and you could walk away $2000 richer!_ 💫💰🌈

**Comment by tusharmath** [comment]
**NOTE:** We will open this PR for everyone to try as an exception

**Comment by ayewo** [comment]
/attempt #750 ✋

1. What’s the deadline?
2. How about making it FCFS?

**Comment by Rutik7066** [comment]
Hi @tusharmath. Is their ant deadline for this?

**Comment by nikhilxe** [comment]
Can i collaborate with you?

**Comment by nikhilxe** [comment]
>  /attempt #750 ✋
> 
> 1. What’s the deadline?
> 2. How about making it FCFS?
> 
> <details id="algora-options">
>   <summary>Options</summary>
>   <ul>
>     <li>
>       <a href="https://console.algora.io/api/bounties/clq53mmfs0004l70fmi8keqzk/cancel-attempt">
>         Cancel my attempt
>       </a>
>     </li>
>   </ul>
> </details>
> 

Can we collaborate on this?

**Comment by nikhilxe** [comment]
> >  /attempt #750 ✋
> > 
> > 1. What’s the deadline?
> > 2. How about making it FCFS?
> > 
> > <details id="algora-options">
> >   <summary>Options</summary>
> >   <ul>
> >     <li>
> >       <a href="https://console.algora.io/api/bounties/clq53mmfs0004l70fmi8keqzk/cancel-attempt">
> >         Cancel my attempt
> >       </a>
> >     </li>
> >   </ul>
> > </details>
> > 
> 
> Can we collaborate on this?

@ayewo

**Comment by puneetkathar1** [comment]
@tusharmath As mentioned in #381 
The main issue to make this WASM compatible is tokio. WASM and Tokio are incompatible. The whole logic of tailcall uses Tokio. Is there any approach you would suggest?

**Comment by ayewo** [comment]
> Can we collaborate on this?

@nikhilxe Too late! I've already accepted someone else's offer to collaborate.

**Comment by tusharmath** [comment]
There is no deadline. Whoever finishes it first shall get the prize :) 

@puneetkathar1 There are going to be parts that will need to be abstracted away specially for wasm compatibility. The meat of the application doesn't change much. Tokio is basically used only in the egress ie http client and we swap that with any client that's support by wasm. The ingress will be powered by cloudflare's SDK, so nothing to worry there.

**Comment by puneetkathar1** [comment]
Hello @ssddOnTop 

I've encountered several errors while attempting to run `wasm-pack build` in my project. I understand that you've made some changes to the libraries, and I'm curious to know if the functionality in the desktop version remains consistent.

I'm currently focusing on the WASM version, and my goal is to ensure that the desktop version remains unchanged while I experiment with the web assembly implementation. I would greatly appreciate any insights or guidance you can provide regarding your approach to handling these aspects.

Thank you in advance for your assistance, and I look forward to hearing from you.

**Comment by ssddOnTop** [comment]
> Hello @ssddOnTop
> 
> I've encountered several errors while attempting to run `wasm-pack build` in the above commit by you. I understand that you've made some changes to the libraries, and I'm curious to know if the functionality in the desktop version remains consistent.
> 
> I was trying to work on this too, my approach was to experiment with WASM version, ensuring that the desktop version remains unchanged. I would greatly appreciate any insights or guidance you can provide regarding your approach to handling these aspects.

The normal version matches main branch exactly and passes all teats. I have WASM function working separately

**Comment by ologbonowiwi** [comment]
shouldn't this be closed @tusharmath?

**Comment by tusharmath** [comment]
There is some related work that's pending. I thought of releasing the bounty a little sooner as a token of appreciation 🙂
